/*
 * generated by Xtext
 */
package org.vaulttec.isis.script;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IsisStandaloneSetup extends IsisStandaloneSetupGenerated {

	public static void doSetup() {
		new IsisStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

